"""Build an OpenAPI 3.0 spec from discovered endpoints.

Target use: import into Acunetix / Burp Pro active scan / fuzzers. We include
API endpoints and anything carrying parameters, and drop static assets. Each
path item carries a per-path `servers` list so multiple hosts fit one file.
"""
from __future__ import annotations

import re
from .urlutil import safe_urlsplit as urlsplit

from .models import Endpoint

_PLACEHOLDER_RE = re.compile(r"\{[^}]+\}")


def _path_params(path: str):
    """Give each {..} placeholder a unique name (id, id2…) and list them."""
    names: list[str] = []

    def repl(_m):
        name = "id" if not names else f"id{len(names) + 1}"
        names.append(name)
        return "{" + name + "}"

    return _PLACEHOLDER_RE.sub(repl, path), names


def _param_schema(name: str) -> dict:
    return {"type": "string"}


def wanted(ep: Endpoint) -> bool:
    if ep.is_static:
        return False
    return ep.is_api or ep.has_param


def build(endpoints: list[Endpoint], host: str | None = None,
          title: str = "jsrecon discovered API") -> dict:
    eps = [e for e in endpoints if wanted(e)]
    if host:
        eps = [e for e in eps if e.host == host]

    paths: dict[str, dict] = {}
    servers_seen: list[str] = []

    for ep in eps:
        parts = urlsplit(ep.url)
        raw_path = ep.path_template or parts.path or "/"
        path, path_param_names = _path_params(raw_path)
        server = f"{ep.scheme}://{ep.host}" if ep.host else ""
        if server and server not in servers_seen:
            servers_seen.append(server)

        method = (ep.method or "GET").lower()
        item = paths.setdefault(path, {})
        op = item.get(method)
        if op is None:
            op = {
                "summary": f"{ep.method} {path}",
                "parameters": [],
                "responses": {"200": {"description": "discovered"}},
                "servers": [],
            }
            if ep.tags:
                op["tags"] = ep.tags
            item[method] = op

        # per-path servers (union across hosts sharing this path+method)
        if server and {"url": server} not in op["servers"]:
            op["servers"].append({"url": server})

        existing = {(p["name"], p["in"]) for p in op["parameters"]}
        for pn in path_param_names:
            if (pn, "path") not in existing:
                op["parameters"].append({
                    "name": pn, "in": "path", "required": True,
                    "schema": {"type": "string"},
                })
                existing.add((pn, "path"))
        for q in ep.query_params:
            if (q, "query") not in existing:
                op["parameters"].append({
                    "name": q, "in": "query", "required": False,
                    "schema": _param_schema(q),
                })
                existing.add((q, "query"))

        if ep.body_params:
            props = {p: {"type": "string"} for p in ep.body_params}
            ct = "application/json"
            if ep.content_type and "json" not in ep.content_type.lower():
                ct = "application/x-www-form-urlencoded"
            op["requestBody"] = {
                "required": False,
                "content": {ct: {"schema": {"type": "object", "properties": props}}},
            }

    # clean up empty per-path server lists
    for item in paths.values():
        for op in item.values():
            if not op.get("servers"):
                op.pop("servers", None)

    spec = {
        "openapi": "3.0.3",
        "info": {"title": title, "version": "1.0.0",
                 "description": "Auto-generated by jsrecon from JS recon."},
        "servers": [{"url": s} for s in servers_seen] or [{"url": "/"}],
        "paths": paths,
    }
    return spec


def host_summary(endpoints: list[Endpoint]) -> list[dict]:
    """List hosts with counts of importable (api/param) endpoints."""
    counts: dict[str, int] = {}
    for ep in endpoints:
        if wanted(ep):
            counts[ep.host] = counts.get(ep.host, 0) + 1
    return sorted(
        ({"host": h, "count": c} for h, c in counts.items()),
        key=lambda x: -x["count"],
    )
